package com.toyota.tfs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AccountHolder implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AccountHolder() {
    }




}