package com.toyota.tfs.decisionservice;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("This class represents the fact that the account has been assigned.")
@org.kie.api.definition.type.Label("Account has been assigned")
public class AccountHasBeenAssigned implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public AccountHasBeenAssigned() {
	}

}