package com.toyota.tfs.decisionservice;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("This object represents the fact that the account has been assigned")
public class Assigned implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public Assigned() {
	}

}