package com.toyota.tfs.decisionservice;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Do not contact")
@org.kie.api.definition.type.Description("This class represents the fact that this account should not be contacted")
public class DoNotContact implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public DoNotContact() {
	}

}