package com.toyota.tfs.decisionservice;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Unassigned implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Unassigned() {
    }




}